"""Portas (interfaces) que o nucleo do Jefrey precisa do mundo de fora. Quem implementa mora em `adapters/outbound`.

Regra da casa: `domain` e `application` so conhecem estas portas, nunca FastAPI, SQLAlchemy, httpx, Windows ou Google.
"""
from __future__ import annotations

from datetime import datetime, timedelta
from typing import Protocol

from src.jefrey.domain.event_alerts import UpcomingEvent
from src.jefrey.domain.google_data import Contact, Task
from src.jefrey.domain.learning import Fact


class CalendarPort(Protocol):
    async def upcoming(self, user_id: str, within: timedelta) -> list[UpcomingEvent]:
        """Compromissos que comecam nos proximos `within`. Lista vazia se a agenda nao esta conectada."""
        ...


class NotifierPort(Protocol):
    def notify(self, user_id: str, title: str, text: str, *, urgent: bool = False) -> bool:
        """Mostra um aviso para a pessoa. True se mostrou."""
        ...


class UserDirectoryPort(Protocol):
    def known_users(self) -> list[str]: ...


class ClockPort(Protocol):
    def now(self) -> datetime:
        """Agora, com fuso."""
        ...


class TasksPort(Protocol):
    async def list_open(self, user_id: str, limit: int = 20) -> "list[Task]": ...
    async def add(self, user_id: str, title: str, due: str = "") -> "Task": ...
    async def complete(self, user_id: str, task_id: str) -> bool: ...


class ContactsPort(Protocol):
    async def all(self, user_id: str) -> "list[Contact]": ...


class FactsPort(Protocol):
    """Fatos aprendidos da pessoa (quem implementa: adapters/outbound/sql_facts.py)."""

    def enabled(self, user_id: str) -> bool: ...
    def learn(self, user_id: str, fact: "Fact") -> str: ...


class WhatsAppStorePort(Protocol):
    """O que o tratamento de mensagens do WhatsApp precisa do armazenamento (quem implementa: adapters/outbound/sql_whatsapp.py)."""

    def touch_chat(self, user_id: str, name: str) -> dict: ...
    def paused(self, user_id: str) -> bool: ...
    def is_new(self, user_id: str, key: str) -> bool: ...
    def recent_drafts(self, user_id: str, chat_id: "str | None", seconds: int) -> int: ...
    def add_draft(self, user_id: str, chat: dict, incoming: str, reply: str, why: str, status: str, msg_ids: "list[str]") -> dict: ...
    def list_chats(self, user_id: str) -> "list[dict]": ...
    def queue_message(self, user_id: str, chat_id: str, text: str) -> dict: ...
    def save_inbox(self, user_id: str, items: "list[dict]") -> "list[dict]": ...
    def inbox_items(self, user_id: str) -> "list[dict]": ...
    def inbox_age_s(self, user_id: str) -> "int | None": ...
    def save_history(self, user_id: str, chat: str, msgs: "list[dict]") -> int: ...
    def history(self, user_id: str, chat: str, limit: int = 10) -> "list[dict]": ...


class PersonContextPort(Protocol):
    """Nome e fatos da pessoa, para escrever no jeito dela."""

    def name(self, user_id: str) -> str: ...
    def known(self, user_id: str) -> "list[str]": ...


class ToolAuditPort(Protocol):
    """Trilha de auditoria das ferramentas (quem implementa: adapters/outbound/runtime_ports.py)."""

    def tool_call(self, *, thread_id: str, tool_name: str, actor_role: str, risk: str, decision: str, reason: "str | None",
                  approval_id: "str | None", approval_decision: "str | None", user_id: str) -> None: ...


class ToolMetricsPort(Protocol):
    def tool_blocked(self, tool: str, reason: str) -> None: ...
    def tool_latency(self, tool: str, seconds: float) -> None: ...


class ApprovalGatePort(Protocol):
    """Aprovacao humana de acoes de risco."""

    def create(self, *, thread_id: str, tool_name: str, arguments: dict, risk_level: str, reason: str, created_by: str, user_id: str) -> str: ...
    async def wait_for_decision(self, approval_id: str, timeout: "float | None" = None) -> str: ...


class OutputGuardPort(Protocol):
    def sanitize(self, text: str, source: str = "") -> str:
        """Tira de texto que veio de fora (web, arquivos, mensagens) o que tenta dar ordens ao modelo."""
        ...


class PrefsPort(Protocol):
    """Preferencias simples da pessoa neste computador."""

    def home_city(self) -> str:
        """Cidade da pessoa para o clima ("" se ainda nao disse)."""
        ...


class AgentEnvPort(Protocol):
    """O que o agente usa do mundo de fora (quem implementa: adapters/outbound/agent_env.py). Lista as pecas que o agente pede."""

    def history_load(self, user_id: str, thread_id: str, limit: int) -> list: ...
    def history_add(self, user_id: str, thread_id: str, user_input: str, answer: str) -> None: ...
    def person_name(self, user_id: str, user_input: str) -> "str | None": ...
    def profile_lines(self, user_id: str) -> "list[str]": ...
    def plain_facts(self, user_id: str) -> "list[str]": ...
    def diary_recent(self, user_id: str, n: int) -> "list[dict]": ...
    def study_lines(self, user_id: str, user_input: str) -> "list[str]": ...
    def touch_activity(self, user_id: str) -> None: ...
    def schedule_diary(self, user_id: str, tz: object) -> None: ...
    def schedule_learning(self, user_id: str, user_input: str, answer: str) -> None: ...
    def load_tools(self, user_id: str) -> "tuple[dict, dict]": ...
    def llm_client(self) -> object: ...
    def model_info(self) -> "tuple[str, str, bool]": ...
    def friendly_error(self, e: Exception) -> str: ...
